### ISSUE TITLE
这个命令，后面到底要不要带参数啊? 谢谢

### ISSUE THREAD

**Issue by ewwerpm** [MollySophia/rwkv-ncnn#3]
![image](https://github.com/MollySophia/rwkv-ncnn/assets/25223652/e373bb2e-ae67-493b-8148-cc120d0363a8)
这个命令，后面到底要不要带参数啊? 谢谢

**Comment by MollySophia** [comment]
> ![image](https://user-images.githubusercontent.com/25223652/268854567-e373bb2e-ae67-493b-8148-cc120d0363a8.png) 这个命令，后面到底要不要带参数啊? 谢谢

抱歉, 下面的示例忘记修改了
是需要的, 具体可以看源码.
